### ISSUE TITLE
Add development tools

### ISSUE THREAD

**Issue by pamelafox** [kjaymiller/Az-Queue-Tweeter#1]
- [x] black
- [ ] flake8
- [x] pre-commit
- [x] pytest

Let me know if you prefer other tools.

**Comment by kjaymiller** [comment]
Poetry currently has `black`, `isort`, and `pytest` as dev dependencies. 

I can see removing `black` and `sort` and adding pre-commit as a test in CI/CD.

**Comment by kjaymiller** [comment]
in the meantime I am going to run black+isort on this and setup pre-commit (outside of gh actions)

**Comment by kjaymiller** [comment]
#13b0f58d8a461d70b75525a490e1ee92660b1c1d - refactors and adds pre-commit.yaml

**Comment by kjaymiller** [comment]
## [ADDED]:
------
- pre-commit
  - black
  - isort
- mypy

## [REMOVED]:
--------
- FROM (pyproject.toml)
  - black
  - isort 

## [NOT ADDED]:
----------
- flake8
