### ISSUE TITLE
Support sending tweets without images as well

### ISSUE THREAD

**Issue by pamelafox** [kjaymiller/Az-Queue-Tweeter#3]

**Comment by kjaymiller** [comment]
I would definitely be interested in seeing the how this is structured in my head I see the `image` or `filename` attributes being an indicator for uploading media (currently this isn't smart and only uploads one image).

I think if there is logic checking for the presence of an image, then definitely something to add.

**Comment by kjaymiller** [comment]
PR #8 actually solves this since the auth model addresses only needing client and sending just a tweet with text

**Comment by kjaymiller** [comment]
resolved in #8 and enhanced with #11
